default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movies_catalog_develop

test:
  <<: *default
  database: movies_catalog_develop

production:
  <<: *default
  database: movies_catalog